### PR TITLE
Markdown support: Is this what you had in mind

### PR DESCRIPTION
**Pull request by microspino**
I'm not sure this is the better way to add support for markdown in m4s2.
I thought a fast library library like sundown would be a good fit for this project: it has zero dependencies and seems fast. Unfortunately sundown development is freezed. Hoedown appear as a mantained substitute. 
Do i have to add **hoedown** as a git submodule?
What do you think? I'm willing to help keeping things minimal.

### CODE REVIEW

**Comment by soveran** [comment]
Hey @microspino! Yes, that's exactly how it should be extended. I won't merge this because I'm fine working with HTML directly, but I think what you did is very valuable for people that want to start from markdown. If it's not a problem for you, can you publish it and maybe with a name like m4m2-markdown? That way I can point people to your repository. If it's problematic, let me know and we can figure out something else. One thing I would change is the way the markdown tool is shipped. Instead of bundling the compiled hoedown, maybe it's better to just give instructions about how to compile it and install it, otherwise it's not guaranteed that it will work for everyone.

Sorry for the delay with my reply, and again thanks a lot for this.

**Comment by microspino** [comment]
I'm fine with your proposal (renamed already) however i would like to contribute to this project (in the spirit of what you said (about.html ;)) ... _"Feel free to ask me for ideas on how to tweak this tool to better suit your needs."_
For example, what about adding just some instructions on how to add markdown to the readme here instead of using my fork? 
I thought also to sass/scss (with [sassc](https://github.com/sass/sassc)) or a [dead simple (responsive) grid](https://github.com/mourner/dead-simple-grid). I can add instructions to integrate them too. 
I don't want to bother so feel free to answer no :)

**Comment by soveran** [comment]
@microspino The instructions are a good idea! We can add pages to the wiki and link to them from the README. Adding instructions for sass and a responsive grid are also great ideas, a lot of people will profit from that. Thanks a lot for contributing!

**Comment by djanowski** [comment]
+1 on adding instructions in the README on how to customize m4s2. 

BTW, users of this tool might find [Hasp](https://github.com/djanowski/hasp) interesting for authoring CSS.

**Pull request closed without merging**
